# Generated by Django 6.0 on 2025-12-28 17:13

import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_product_unique_together_alter_brand_api_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='api_key',
            field=models.CharField(default=licenses.models.generate_api_key, editable=False, max_length=80, unique=True),
        ),
        migrations.AddConstraint(
            model_name='activation',
            constraint=models.UniqueConstraint(fields=('license', 'instance_id'), name='uniq_license_instance'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'code'), name='uniq_brand_product_code'),
        ),
    ]
